apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-claim
  namespace: work-space
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 100Gi