apiVersion: v1
kind: Secret
metadata:
  name: mariadb-pass
  namespace: work-space
  labels:
    app: mariadb
data:
  # This value is base64-encoded. Do not use this password in production! (password)
  password: cGFzc3dvcmQ=

