kind: Service
apiVersion: v1
metadata:
  name: nfs-server
  namespace: work-space
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  clusterIP: 10.43.184.231 # Cluster ip can be adapted; is optional
  selector:
    app: nfs-server
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-mariadb
  namespace: work-space
  labels:
    app: mariadb
spec:
  ports:
    - port: 3306
  selector:
    app: mariadb
    tier: mariadb
  clusterIP: 10.43.184.232
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-client
  namespace: work-space
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30880
  selector:
    name: webapp-client
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-server
  namespace: work-space
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500
  selector:
    name: webapp-server
