version: '3.8'
services:
  client:
    # platform: linux/arm64
    build: ./client
    ports:
      - 8080:8080
    # networks:
    #   - serverClientNet

  server:
    # platform: linux/arm64
    build: ./server
    depends_on:
      - mariadb
    # networks:
    #   - serverClientNet
    #   - serverDatabaseNet
    ports:
      - 5000:5000

  mariadb:
    image: mariadb
    restart: always
    # command: --init-file /var/lib/mysql/init_database_and_table.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql
      - ./data/sql_scripts:/docker-entrypoint-initdb.d
    # networks:
    #   - serverDatabaseNet
    ports:
      - 3306:3306

# networks:
#   serverClientNet:
#   serverDatabaseNet:
